spring:
    application:
        name: network-store-server
    datasource:
        url: ${dbUrl}
        username: ${login}
        password: ${password}

server:
    port: 8080
    forward-headers-strategy: framework

cassandra-keyspace: iidm

logging:
    level:
         ROOT: INFO

# this structure is shared among all microservices, if you change it, change it everywhere
# customQuery allows a microservice to set query parameters specific to itself
# if customQuery is empty, set queryBegin to "?", otherwise set it to "&"
# this allow the user to add additional query elements common to all microservices
# and using the appropriate leading character depending on whether the microsevice
# uses custom query parameters
queryBegin: '&'
customQuery: ?reWriteBatchedInserts=true
dbName: iidm
dbApi: jdbc
