spring:
    application:
        name: network-store-server
    datasource:
        url: ${dbApi}:${dbVendor}://${hostPort}/${dbName}${query}
        username: ${login}
        password: ${password}

server:
    port: 8080
    forward-headers-strategy: framework

cassandra-keyspace: iidm

logging:
    level:
         ROOT: INFO

dbName: iidm
dbApi: jdbc
